module.exports = {
  EmailName: 'name',
  FromAddress: 'fromEmail',
  FromName: 'fromName',
  Subject: 'subject',
  PreviewURL: 'url',
  Status: 'status',
  SentDate: 'sentDate',
  NumberSent: 'metrics.sent',
  NumberDelivered: 'metrics.delivered',
  UniqueOpens: 'metrics.uniqueOpens',
  UniqueClicks: 'metrics.uniqueClicks',
  Unsubscribes: 'metrics.unsubscribes',
  ForwardedEmails: 'metrics.forwards',
};
