version: '3.7'

x-env-defaults: &env
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_ACCOUNT_ID: 598984531759
  AWS_REGION: us-east-2
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  FUEL_API_CLIENT_ID: ${FUEL_API_CLIENT_ID}
  FUEL_API_CLIENT_SECRET: ${FUEL_API_CLIENT_SECRET}
  FUEL_API_AUTH_URL: ${FUEL_API_AUTH_URL}
  FUEL_API_ACCOUNT_ID: ${FUEL_API_ACCOUNT_ID}
  CLICK_LOG_CUSTOMER_KEY: ${CLICK_LOG_CUSTOMER_KEY-Click Log}
  CLICK_LOG_OBJECT_ID: ${CLICK_LOG_OBJECT_ID-9fa00068-aa22-e611-ba56-00110a68cc95}
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  MONGO_DB_NAME: ${MONGO_DB_NAME-leads-sync}
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:12.15-alpine
  working_dir: /sync
  restart: always
  volumes:
    - .:/sync:cached
    - ./node_modules:/sync/node_modules:delegated
  environment:
    <<: *env

x-test-command: &test
  <<: *node
  working_dir: /sync/src
  entrypoint: ["node", "test"]
  environment:
    <<: *env
  depends_on:
    - mongodb

services:
  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "43987:27017"

  queue-events:
    <<: *test
    command: ["queue-events"]

  process-events:
    <<: *test
    command: ["process-events"]

  mark-as-processed:
    <<: *test
    command: ["mark-as-processed"]

  script-event-sends:
    <<: *test
    working_dir: /sync/src/scripts
    entrypoint: ["node", "event-sends"]

  script-event-subs:
    <<: *test
    working_dir: /sync/src/scripts
    entrypoint: ["node", "event-subs"]

volumes:
  mongodb: {}
